name: Maven Compile and Format

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  format-and-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Compile the project
        run: cd JabberPointSQ && mvn clean compile

      - name: Apply Google Java Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}
