name: Release Build

on:
  pull_request:
    types: [closed]
    branches: ["main"]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"
          cache: maven

      - name: Package the application
        run: cd JabberPointSQ && mvn clean test jacoco:report

      - name: Get project version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
