name: Test Coverage

on:
  push:
    branches: ["testing"]
  pull_request:
    branches: ["testing"]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"
          cache: maven

      - name: Run unit tests
        run: cd JabberPointSQ && mvn clean test jacoco:report

      - name: Upload coverage report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: JabberPointSQ/target/site/jacoco/

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: GabrielGuevaraLopez/jabberSQ
